### ISSUE TITLE
Checklist of things I need to get done before launch

### ISSUE THREAD

**Issue by Visual-Studio-Coder** [Visual-Studio-Coder/Loc-Reminder-SwiftUI#1]
- [x] Fix onboarding (hide the pagination dots unless the permission has been provided)
- [x] Make transition from onboarding to actual content look nicer (fade out maybe?)
- [ ] Make Spot previews look nicer (show the location coordinates, address, possibly an icon?)
- [x] Fix location based notifications
- [ ] Populate About page

Extra Credit
- [ ] Make keyboard "next" button scroll to next elements of form and focus keyboard
- [ ] Notification logs
- [ ] Widgets? (maybe extra credit pro ultra max)
